from pydantic import BaseModel, Field
from typing import Dict, Any, Optional

class ChatRequest(BaseModel):
    message: str = Field(..., description="The natural language message sent by the medical representative")
    session_id: Optional[str] = Field(default=None, description="The unique session ID to track conversation state history")
    current_form_state: Optional[Dict[str, Any]] = Field(default_factory=dict, description="The current client-side form values")

class ChatResponse(BaseModel):
    message: str = Field(..., description="The natural language response generated by the AI assistant")
    extracted_form_fields: Dict[str, Any] = Field(..., description="The parsed/extracted CRM form state fields")
    intent: str = Field(..., description="The classified user intent (e.g. Log Interaction, Search HCP)")
